# Generated by Django 6.0 on 2026-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
