# Generated by Django 6.0 on 2026-03-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOTES', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
