# Generated by Django 6.0 on 2026-05-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOTES', '0002_alter_stage_options_stage_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='created_at',
        ),
    ]
